{{- if .Values.vpa.keda.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: keda-operator-vpa
  namespace: {{ .Release.Namespace }}
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: {{ .Values.operator.name }}
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        controlledResources:
          - cpu
          - memory
        maxAllowed:
          cpu: {{ .Values.vpa.keda.cpu.maxAllowed }}
          memory: {{ .Values.vpa.keda.memory.maxAllowed }}
        minAllowed:
          cpu: {{ .Values.vpa.keda.cpu.minAllowed }}
          memory: {{ .Values.vpa.keda.memory.minAllowed }}
  updatePolicy:
    updateMode: "Auto"
{{- end }}
